# Generated by Django 3.0.4 on 2020-03-29 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when_finished',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
