# Generated by Django 3.0.4 on 2020-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_when_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when_finished_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
