# Generated by Django 3.0.4 on 2020-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_when_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='when_finished_h',
            field=models.TimeField(default=None),
        ),
    ]
